#!/usr/bin/env bash

displayUsage() {
      cat $BASEDIR/docker.hlp 2>/dev/null || true
}

BASEDIR=$(dirname $(readlink -f $0))
COMMAND="$1"

pushd $BASEDIR

case `awk '{print tolower($0)}' <<< "$COMMAND"` in
	build)
		docker-compose -f $BASEDIR/docker-compose.yml build
	;;
	up)
		docker-compose -f $BASEDIR/docker-compose.yml up -d
	;;
	exec)
		docker-compose -f $BASEDIR/docker-compose.yml exec builder bash
	;;
	down)
		docker-compose -f $BASEDIR/docker-compose.yml down
	;;
	*) displayUsage; exit 139
	;;
esac
